config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
                                       :registrations => "registrations" }

  root 'stalls#index'
  resources :stalls do
    resources :events
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :stall
end

app/models/stall.rb
class Stall < ActiveRecord::Base
	validates :user_id, presence: true
	belongs_to :user
  geocoded_by :address
  after_validation :geocode
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  attr_accessor :user_location

  has_many :events, dependent: :destroy 

  has_attached_file :menu_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :menu_image, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :stalls, dependent: :destroy 
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }

  devise :omniauthable, :omniauth_providers => [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    #user.name = auth.info.name   # assuming the user model has a name
	    #user.image = auth.info.image # assuming the user model has an image
	  end
	end       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show

  end

  def new
    @stalls = Stall.find(params[:stall_id])
    @event = @stalls.events.build
  end

  def edit
  end

  def create
    @stalls = Stall.find(params[:stall_id])
    @event = @stalls.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @stalls, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :start_time, :date, :location, :stall_id)
    end
end

app/controllers/registration_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/controllers/stalls_controller.rb
class StallsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    if (params[:user_location])
      @stalls = Stall.near(params[:user_location], 10)
      @stalls_filter = Stall.near(params[:user_location], 10)
    else
      @stalls = Stall.all
    end
  end

  def index_info
    @stalls_filter = Stall.near(params[:user_location], 10)
  end

  def new
    @stall = current_user.stalls.build
  end

  def create

    @stall = current_user.stalls.build(stall_params)
    if @stall.save
      flash[:notice] = "Your stall has been created!"
      redirect_to stalls_path
    else
      flash[:alert] = "Your new stall couldn't be created!  Please check the form."
      render :new
    end
  end

  def show
    @stall = Stall.find(params[:id])
    @events = @stall.events.all
  end

  def edit
    @stall = Stall.find(params[:id])
  end

  def update
    @stall = Stall.find(params[:id])
    @stall.update(stall_params)
    redirect_to '/stalls'
  end

  def destroy
    @stall = Stall.find(params[:id])
    @stall.destroy
    flash[:notice] = 'Stall deleted successfully'
    redirect_to '/stalls'
  end

  private

  def stall_params
    params.require(:stall).permit(:name, :description, :address,:image,:menu_image, :user_location)
  end

  def owned_post
    @stall = Stall.find(params[:id])
    unless current_user == @stall.user
      flash[:alert] = "That stall doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook

    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication 
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/stalls_helper.rb
module StallsHelper
end

app/views/events/_form.html.erb
<%= form_for([@event.stall, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :start_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.start_time %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_stall_event_path(params[:id]) %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', stall_path(@stalls) %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StreetFood</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>

	<body>
    <ul>
  	  <% if user_signed_in? %>
        <li>
  	  	  <%= link_to "Create New Stall", new_stall_path, :class => "link"  %>
        </li>
        <li>
          <%= link_to "Show Stalls", stalls_path, :class => "link" %>
        </li>
        <li>
  	  	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "link" %>
        </li>
  	  <% else %>
        <li>
          <%= link_to "Login", new_user_session_path, :class => "link" %>
        </li>
        <li>
  			  <%= link_to "Register", new_user_registration_path, :class => "link" %>
        </li>
        <li>
          <%= link_to "Show Stalls", stalls_path, :class => "link" %>
        </li>
  	  <% end %>
    </ul>
		<%= notice %>
		<%= yield %>

	</body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, :class => "link" %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, :class => "link" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, :class => "links"%>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, :class => "links" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= start_date.strftime("%U").to_i %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/stalls/_filter_map.html.erb
<div class="card">
  <div class="card-block">
    <div id="map" style="width: 400px; height: 400px"></div>
  </div>
</div>

app/views/stalls/_form.html.erb

<%= form_for @stall, html: {multipart: true}, :class => "forms" do |f| %>
<div id="form-field">
    <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :image %>
  <%= f.file_field :image %><br>
  <%= f.label :description %>
  <%= f.text_field :description %><br>
  <%= f.label :menu_image %>
  <%= f.file_field :menu_image %><br>
  <%= f.label :address %>
  <%= f.text_field :address %><br>
  <%= f.submit %>
</div>
<% end %>

app/views/stalls/_map.html.erb
<div class="card">
  <div class="card-block">
    <div id="map" style="width: 400px; height: 400px"></div>
  </div>
</div>

<% my_url = "http://maps.googleapis.com/maps/api/staticmap?center=#{@stalls_filter.first.latitude},#{@stalls_filter.first.longitude}&zoom=12.7&size=640x400&key=AIzaSyCZ4K0_zcXxMjm6RwvYCczETWkr0CELFy4" %>
<% @stalls_filter.each do |stall| %>
  <% my_url += "&markers=#{stall.latitude}%2C#{stall.longitude}" %>
<% end %>
<%= image_tag my_url %>

app/views/stalls/_user_location.html.erb
<%= form_tag("/stalls",method:"get")do %>
  <%= label_tag(:user_location, "Where are you?") %>
  <%= text_field_tag :user_location %>

  <%= submit_tag("Submit") %>
<% end %>

app/views/stalls/edit.html.erb
<%= render "form" %>

app/views/stalls/index.html.erb
<div class="background-box">
  <br><%= render "user_location" %>

<br><% if @stalls.any? %>
  <% @stalls.each do |stall| %>
    <%= link_to stall.name, stall_path(stall), :class => "link" %><br>
    <%= image_tag stall.image.url(:medium), :class => "images" %><br>

    <div class="description-address">
      Description: <%= stall.description %><br>
      Address: <%= stall.address %><br>
    </div>


      <% if current_user == stall.user %>
      <ul class="small-under-bar">
        <li>
          <%= link_to "Edit", edit_stall_path(stall), :class => "bottom-link" %>
        </li>
        <li>
          <%= link_to "Delete", stall_path(stall), :class => "bottom-link", method: :delete %>
        </li>
        </ul>
      <% end %>

  <% end %>
<% else %>
  No stalls yet
<% end %>

<% if @stalls_filter %>
  <%= render "filter_map" %>
<% end %>
</div>

app/views/stalls/new.html.erb
<%= render "form"%>

app/views/stalls/show.html.erb
<div class="background-box">

  <p class="title"><%= @stall.name %></p>

  <%= image_tag @stall.image.url(:medium), :class => "images" %>
  <%= image_tag @stall.menu_image.url(:medium), :class => "images" %><br>

  <div class="description-address">
    Description:  <%= @stall.description %><br>
    Address:  <%= @stall.address %><br>
  </div>

  <%= image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{@stall.latitude},#{@stall.longitude}&markers=#{@stall.latitude},#{@stall.longitude}&zoom=15&size=640x400&key=AIzaSyCZ4K0_zcXxMjm6RwvYCczETWkr0CELFy4",
              class: 'img-fluid img-rounded', alt: "#{@stall.name} on the map"%>
  <br>

<div class="simple-calendar">
  <div class="calendar-heading">
    <% if @events %>
      <%= month_calendar events: @events do |date, events| %>
        <%= date.strftime("%d") %>
        <% events.each do |event| %>
          <div>
            <%= event.name %>
            <%= event.location %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

  <ul class="under-bar">
    <% if @stall.user == current_user%>
      <li>
        <%= link_to 'Create New Event', new_stall_event_path(@stall), :class => "bottom-link" %>
      </li>
      <li>
        <%= link_to "Edit Stall", edit_stall_path(@stall), :class => "bottom-link" %>
      </li>
      <li>
        <%= link_to "Delete Stall", stall_path(@stall), :class => "bottom-link", method: :delete %>
      </li>
      <li>
        <%= link_to  "Home", stalls_path, :class => "bottom-link" %>
      </li>
    <% else %>
      <li>
        <%= link_to  "Home", stalls_path, :class => "bottom-link" %>
      </li>
    <% end %>
  </ul>
</div>